export default {
    REPLACE_USER_INFO: 'REPLACE_USER_INFO',
    CLEAR_USER_INFO: 'CLEAR_USER_INFO',
    STORE:'http://127.0.0.1/my-store/index.php/Home/Store/',
    ALL_CARTS_PRODUCTS: 'ALL_CARTS_PRODUCTS',
    EDIT_CART: 'EDIT_CART',
    CHOOSE_CART: 'CHOOSE_CART',
    CHOOSE_ALL: 'CHOOSE_ALL',
    ADD_CART_PRODUCT: 'ADD_CART_PRODUCT',
    DEL_CART_PRODUCT: 'DEL_CART_PRODUCT',
    GET_CART_INFO: 'GET_CART_INFO',
    ASSIGN_SETTLE_CHOOSEIDS: 'ASSIGN_SETTLE_CHOOSEIDS',
    CARTS_REMARK: 'CARTS_REMARK',//留言
    REMOVE_CART_BY_ID: 'REMOVE_CART_BY_ID',//删除购物车商品
    ADD_CART: 'ADD_CART',//加入购物车
    PRODETAILS_INIT: 'PRODETAILS_INIT',//商品详情
    PRODUCT_COLLECTION: 'PRODUCT_COLLECTION',//收藏商品
    SHOW_PRO_SPEC: 'SHOW_PRO_SPEC',//显示商品规格
    HIDE_PRO_SPEC: 'HIDE_PRO_SPEC',//隐藏商品规格
    CHOOSE_ATTR: 'CHOOSE_ATTR',//选择商品规格
    ADD_CART_PRODUCT_NUMBER: 'ADD_CART_PRODUCT_NUMBER',//商品详情页中增加商品个数
    DEL_CART_PRODUCT_NUMBER: 'DEL_CART_PRODUCT_NUMBER',//商品详情页中减少商品个数
    GET_DEFAULT_ADDRESS: 'GET_DEFAULT_ADDRESS',//读取默认地址
    GET_MY_ADDRESSES: 'GET_MY_ADDRESSES',//读取个人地址列表
    SET_DEFAULT_ADDRESS: 'SET_DEFAULT_ADDRESS',//设置默认地址
    ADD_ADDRESS: 'ADD_ADDRESS',//添加地址
    GET_PRODUCTS: 'GET_PRODUCTS',//获取商品列表
    CANCEL_SEARCH: 'CANCEL_SEARCH',//取消搜索
    SEARCH_PRO: 'SEARCH_PRO',//搜索商品
    SCROLL_POSITION: 'SCROLL_POSITION',//滑动位置
    SEARCH_SCROLL_GET_MORE_PRO: 'SEARCH_SCROLL_GET_MORE_PRO',//搜多页面滚动加载更多
    INDEX_INIT: 'INDEX_INIT',//首页初始化
    MY_INIT:'MY_INIT'//个人信息初始化
}
